# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - libv8-dev

repos: 
  CRAN: https://cran.rstudio.com
  
os:
 - linux
 - osx
