# Features {#features}

## PrAnaViz

We have created a web-based interactive tool, `PrAnaViz`, in a familiar **dashboard layout** with two tabs: (1) **Targeted API**, (2) **Non-targeted API**, to visualize total quantity of different APIs at CCG region with resolution to individual postcode. 

### Targeted Approach

- In this tab, user can **input a list of APIs**, and find out the **total prescription quantity** of each API in the selected year, at the selected CCG region.
- This tab also visualise the total quantity of **APIs** prescribed by  month, GP, Chemical form, and  Medicinal form for a CCG region in a selected year.

### Non-targeted Approach

- Total prescription quantity of an individual API at **different postcode per month** at a CCG region, can be rendered in this tab.
- The calculated total prescription quantity of an individual API at postcode level helps to find **the hotspots**.
- User can download data as **_.csv_** file and publication ready image **_.eps_** and **_.pdf_** files.
