--- 
title: "PrAna Handbook"
author: "Kishore Jagadeesan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: 
  - references.bib
  - packages.bib
biblio-style: apalike
link-citations: yes
colorlinks: yes
graphics: yes
lot: yes
lof: yes
fontsize: 11pt
mainfont: Palatino
description: "This is a handbook to use the PrAna package to aggregate and normalise England’s national level prescription data."
---

# Introduction

During the last decade, wide range of **active pharmaceutical ingredients (APIs)** have been identified and quantified in aquatic environment across several studies and indicated their impacts on exposed environmental species and humans. For the prediction of total amount of the APIs released to the environment, information about APIs consumption data is vital. Globally, several methods were reported to estimate the APIs consumption data based on the national prescription data, manufacturers, importers and dispenser’s data.

In the UK, national prescription data provided by [**National Health Service (NHS)**][NHS], was used to calculate the consumption data. This data is freely accessible and consist of individual files for each month. With the large file with over 10 million records every month, the data from the NHS cannot be used for the direct calculation of the prescription levels of different APIs. Re-organisation and processing of the files is required before to do any exploration or analysis and to speed up the data reading. 

The aim of `PrAna` is to aggregate and normalize prescription data to calculate **total prescribed quantity** of different APIs, using open source statistical software [R language][R].  The name is an acronym for _**Pr**escription **Ana**lysis_

Apart, from the calculation of the total prescribed quantity of an API or a group of APIs, specified to a postcode or region, We have also developed, _an open interactive web-based tool_, `PrAnaViz` with the processed dataset for the period `2015` to `2018`.

`PrAnaViz` facilitates users **to visualise, explore and report** different spatiotemporal and long-term prescription trends for wider use. 

The documentation of `PrAna` consists of three parts:

- This handbook
- The reference manual (accessible in `R` with `?PrAna-package` or [online here][PrAna ref])
- A tutorial for PrAnaViz [(accessible at here)][PrAnaViz Tutorial]
- A tutorial for FileUpload [(accessible at here)][FileUpload Tutorial]

[R]: https://www.r-project.org/
[NHS]: https://digital.nhs.uk/organisation-data-service/data-downloads/gp-data
[PrAna ref]: https://github.bath.ac.uk/kjj28/PrAna/reference/index.html
